config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  
  devise_for :freelancers
  devise_for :contractors

  namespace :api do
    namespace :v1 do
      resources :projects, only: %i[index show create]
    end
  end

  resources :contractors, only: [:show]
  resources :freelancers, only: [:show, :edit, :update] do
    get 'my_projects', on: :collection
  end

  resources :projects, shallow: true do
    get 'search', on: :collection
    get 'close', on: :member
    get 'finish', on: :member
    resources :proposals do
      post 'accept', on: :member
      post 'deny', on: :member
      post 'forfeit', on: :member
      post 'archive', on: :member
      resource :feedback, only: [:new, :create]
      resources :chats do
        get 'create_new_chat_window', on: :collection
      end
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :contractor
  belongs_to :freelancer_expertise
  has_many :proposals
  has_many :chats, through: :proposals

  enum status: { opened: 0, closed: 10, finished: 20 }

  validates :title, :description, :desired_skills, :top_hourly_wage, :proposal_deadline,
            presence: true

  validate :positive_top_hourly_wage

  private

  def positive_top_hourly_wage
    errors.add(:top_hourly_wage, 'não pode ser negativo') if !top_hourly_wage.nil? && top_hourly_wage.negative?
  end
end

app/controllers/api/v1/projects_controller.rb
module Api
  module V1
    class ProjectsController < ApiController
      def index
        @projects = Project.all
        render json: @projects.as_json(include: { contractor: { only: [:email] } })
      end

      def show
        @project = Project.find(params[:id])
        render json: @project
      end

      def create
        @project = Project.create(params.require(:project)
                                        .permit(:title, :description,
                                                :desired_skills,
                                                :top_hourly_wage,
                                                :proposal_deadline,
                                                :remote,
                                                :freelancer_expertise_id,
                                                :contractor_id))
        render json: @project, status: 201
      end
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_contractor!,
                only: %i[new create edit update close finish destroy]
  before_action :authenticate_any!, only: [:search]
  before_action :check_project_contractor, only: %i[edit update close finish destroy]

  def show
    @project = Project.find(params[:id])
    @proposal = Proposal.new
    @proposals = Proposal.where(project: Project.find(params[:id]), archived: false)
    @chat = Chat.new
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params.require(:project).permit(:title, :description, :desired_skills,
                                                           :top_hourly_wage, :proposal_deadline,
                                                           :remote, :freelancer_expertise_id))
    @project.contractor = current_contractor
    if @project.save
      redirect_to(project_path(@project))
    else
      render :new, alert: 'não conseguiu salvar'
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(params.require(:project).permit(:title, :description, :desired_skills,
                                                       :top_hourly_wage, :proposal_deadline,
                                                       :remote, :freelancer_expertise_id))
      redirect_to project_path @project
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to root_path
  end

  def search
    # Vulnerable to SQL injection
    # Investigar melhor o having caso dê tempo
    # https://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-having

    @projects = (Project.where('title LIKE ?',
                               "%#{search_strip}%").and(Project.where(status: 'opened')))
                .or((Project.where('description LIKE ?',
                                   "%#{search_strip}%")).and(Project.where(status: 'opened')))
  end

  def close
    @project.closed!
    @proposals = Proposal.where(project: @project)
    @proposals.each do |proposal|
      proposal.proposal_denied!
      Feedback.create(proposal: proposal,
                      body: 'Contratante fechou projeto para recebimento de novas propostas')
    end
    redirect_to project_path(@project)
  end

  def finish
    @project.finished!
    redirect_to project_path(@project)
  end

  private

  def check_project_contractor
    @project = Project.find(params[:id])
    return unless @project.contractor != current_contractor

    flash[:notice] = 'VOCÊ NÃO POSSUI ACESSO A ESTE PROJETO'
    redirect_to project_path @project
  end
end

app/views/projects/_form.html.erb
<%= form_with model: project do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= project.errors.full_messages_for(:title)[0] %>
  <br />
  <br />
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= project.errors.full_messages_for(:description)[0] %>
  <br />
  <br />
  <%= f.label :desired_skills %>
  <%= f.text_field :desired_skills %>
  <%= project.errors.full_messages_for(:desired_skills)[0] %>
  <br />
  <br />
  <%= f.label :top_hourly_wage %>
  <%= f.number_field :top_hourly_wage %>
  <%= project.errors.full_messages_for(:top_hourly_wage)[0] %>
  <br />
  <br />
  <%= f.label :proposal_deadline %>
  <%= f.date_field :proposal_deadline %>
  <%= project.errors.full_messages_for(:proposal_deadline)[0] %>
  <br />
  <br />
  <%= f.label :remote %>
  <%= f.check_box :remote %>
  <br />
  <%= f.label :freelancer_expertise_id %>
  <%= f.collection_select(:freelancer_expertise_id, FreelancerExpertise.all, :id, :title, {:prompt => 'Selecionar opção'}) %>
  <%= project.errors.full_messages_for(:freelancer_expertise)[0] %>
  <br />
  <br />
  <%= f.submit "Salvar Projeto", class: "btn btn-primary" %>
<% end %>

app/views/projects/_summary_list_of_projects.html.erb
<% if projects.blank? %>
    <p> Ainda não existem projetos cadastrados </p>
<% else %>
  <% projects.each do |project| %>
    <%= link_to project.title, project_path(project) %>
    <br />
    <%= project.description %>
    <br />
    <%= project.desired_skills %>
    <br />
    <br />
  <% end %>
<% end %>

app/views/projects/edit.html.erb
<h1> Página de cadastro de edição de projeto </h1>

<%= render 'form', project: @project %>

app/views/projects/new.html.erb
<h1> Página de cadastro de novo projeto </h1>

<%= render 'form', project: @project %>

app/views/projects/search.html.erb
<h2> Lista de projetos pesquisados </h2>
<%= render 'summary_list_of_projects', projects: @projects %>

app/views/projects/show.html.erb
<h1> <%= @project.title %> </h1>
<p>
<% if Project.human_attribute_name("status.#{@project.status}") == 'Fechado'%>
    RECEBIMENTO DE PROPOSTAS PARA PROJETO ENCERRADAS
<% end %>
<br />
Descrição do projeto: <%= @project.description %>
<br />
O que procuramos no freela: <%= @project.desired_skills %>
<br />
Área de atuação requerida: <%= @project.freelancer_expertise.title %>
<br />
Máximo preço por hora: <%= number_to_currency @project.top_hourly_wage %>
<br />
Data limite para envio de propostas: <%= l @project.proposal_deadline %>
<br />
<% if @project.remote %>
    Trabalho remoto: sim
<% else %>
    Trabalho remoto: não
<% end %>
</p>

<% if contractor_signed_in? && current_contractor == @project.contractor %>
    <%= link_to 'Editar informações do projeto', edit_project_path %>
    <br />
    <%= link_to 'Remover projeto', @project, method: :delete, data: { confirm: 'Você tem certeza?'} %>
    <br />
    <%= link_to 'Encerrar inscrições', close_project_path(@project) %>
    <br />
    <%= link_to 'Fechar projeto', finish_project_path(@project) %>
    <% if @project.finished? %>
        PROJETO ENCERRADO
    <% end %>

    <% if @proposals.where(status: 'proposal_approved').any? %>
        <h4> Time de freelancers contratados para o projeto: </h4>
            <% @proposals.where(status: 'proposal_approved').each do |p| %>
                Nome social: <%= p.freelancer.social_name %>
                <br />
                Descrição do profissional: <%= p.freelancer.description %>
                <br />
                Justificativa para o projeto: <%= p.proposal_description %>
                <br />
                Área de atuação: <%= p.freelancer.freelancer_expertise.title %>
                <br />
                <br />
            <% end %>
        <% end %>

    <h3> Propostas recebidas: </h3>

    <% @proposals.each do |proposal| %>
        <%= link_to proposal.freelancer.social_name, freelancer_path(proposal.freelancer) %>
        <br />
        Descrição do profissional: <%= proposal.freelancer.description %>
        <br />
        Justificativa para o projeto: <%= proposal.proposal_description %>
        <br />
        Carga horária semanal: <%= proposal.weekly_hours %> horas
        <br />
        Conclusão do projeto em: <%= I18n.l proposal.expected_conclusion %>
        <br />
        Valor/hora: <%= number_to_currency(proposal.hourly_wage) %>
        <br />
        Status da proposta: <%= Proposal.human_attribute_name("status.#{proposal.status}") %>
        <br />
        <% if Proposal.human_attribute_name("status.#{proposal.status}") == 'Pendente' %>
            <%= link_to 'Aprovar proposta', accept_proposal_path(proposal), method: :post %>
            &emsp;
            <%= link_to 'Recusar proposta', deny_proposal_path(proposal), method: :post %>
        <% elsif Proposal.human_attribute_name("status.#{proposal.status}") == 'Recusada' %>
            Motivo: <%= proposal.feedback.body %>
        <% else %>
            <%= link_to 'Ir para chat', proposal_path(proposal) %>
        <% end %>
        <br />
        <br />
    <% end %>


<% elsif freelancer_signed_in? %>
    <% if Project.human_attribute_name("status.#{@project.status}") == 'Aberto' %>
        <h3> Adicione sua proposta de trabalho! </h3>
        <%= form_with model: @proposal, url: project_proposals_path(@project) do |f| %>
            <%= @proposal.errors.full_messages_for(:freelancer_id)[0] %>
            <br />
            <%= f.label :proposal_description %>
            <%= f.text_field :proposal_description %>
            <%= @proposal.errors.full_messages_for(:proposal_description)[0] %>
            <br />
            <%= f.label :hourly_wage %>
            <%= f.number_field :hourly_wage %>
            <%= @proposal.errors.full_messages_for(:hourly_wage)[0] %>
            <br />
            <%= f.label :weekly_hours %>
            <%= f.number_field :weekly_hours %>
            <%= @proposal.errors.full_messages_for(:weekly_hours)[0] %>
            <br />
            <%= f.label :expected_conclusion %>
            <%= f.date_field :expected_conclusion %>
            <%= @proposal.errors.full_messages_for(:expected_conclusion)[0] %>
            <%= f.submit 'Enviar proposta', class: "btn btn-primary" %>
        <% end %>
    <% end %>

    <h4> Suas propostas: </h4>
    <% @proposals.each do |proposal| %>
        <% if proposal.archived == false && proposal.freelancer == current_freelancer %>
            <% if %>
                Justificativa: <%= proposal.proposal_description %>
                <br />
                Valor/hora: <%= number_to_currency proposal.hourly_wage %>
                <br />
                Carga horária semanal: <%= proposal.weekly_hours %> horas
                <br />
                Conclusão esperada: <%= l proposal.expected_conclusion %>
                <br />
                Status da proposta: <%= Proposal.human_attribute_name("status.#{proposal.status}") %>
                <br />
                <% if Proposal.human_attribute_name("status.#{proposal.status}") == 'Pendente' %>
                    <%= link_to 'Desistir de proposta', archive_proposal_path(proposal), method: :post, data: { confirm: 'Você tem certeza?'} %>
                    <br />
                <% elsif Proposal.human_attribute_name("status.#{proposal.status}") == 'Recusada' %>
                    Motivo: <%= proposal.feedback.body %>
                    <br />
                <% elsif Proposal.human_attribute_name("status.#{proposal.status}") == 'Aprovada' %>
                    <%= link_to 'Ir para chat', proposal_path(proposal) %>
                    &emsp;
                    <%= link_to 'Desistir de proposta', forfeit_proposal_path(proposal), method: :post %>
                    <h4> Time do projeto: </h4>
                    <% @proposals.where(status: 'proposal_approved').each do |p| %>
                        Nome social: <%= p.freelancer.social_name %>
                        <br />
                        Descrição do profissional: <%= p.freelancer.description %>
                        <br />
                        Justificativa para o projeto: <%= p.proposal_description %>
                        <br />
                        Área de atuação: <%= p.freelancer.freelancer_expertise.title %>
                        <br />
                        <br />
                    <% end %>
                <% else %>
                    Motivo da desistência: <%= proposal.feedback.body %>
                <% end %>
                <br />
            <% end %>
        <% end %>
    <% end %>



<% end %>

<%= link_to 'Voltar', root_path %>