config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  
  devise_for :freelancers
  devise_for :contractors

  namespace :api do
    namespace :v1 do
      resources :projects, only: %i[index show create]
    end
  end

  resources :contractors, only: [:show]
  resources :freelancers, only: [:show, :edit, :update] do
    get 'my_projects', on: :collection
  end

  resources :projects, shallow: true do
    get 'search', on: :collection
    get 'close', on: :member
    get 'finish', on: :member
    resources :proposals do
      post 'accept', on: :member
      post 'deny', on: :member
      post 'forfeit', on: :member
      post 'archive', on: :member
      resource :feedback, only: [:new, :create]
      resources :chats do
        get 'create_new_chat_window', on: :collection
      end
    end
  end
end

app/models/freelancer.rb
class Freelancer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  belongs_to :freelancer_expertise, optional: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :proposals
  # has_many :chats, through: :proposals

  has_many :projects, through: :proposals
  validates :full_name, :social_name, :birth_date, :degree, :description, :experience,
            :freelancer_expertise, presence: true, on: :profile_completion
  validate :check_if_underage

  private

  def check_if_underage
    return unless birth_date.present? && birth_date > 18.years.ago

    errors.add(:birth_date,
               "deve ser anterior a #{I18n.l 18.years.ago}")
  end
end

app/controllers/freelancers_controller.rb
class FreelancersController < ApplicationController
  before_action :authenticate_freelancer!, :check_freelancer_identity,
                only: %i[edit update my_projects]
  before_action :authenticate_any!, :check_freelancer_identity, only: [:show]

  def show
    if freelancer_signed_in?
      @freelancer = current_freelancer
      @projects = @freelancer.projects.where(status: 'finished')
    elsif contractor_signed_in?
      @freelancer = Freelancer.find(params[:id])
    end
  end

  def edit
    @freelancer = current_freelancer
  end

  def update
    @freelancer = current_freelancer
    @freelancer.update(params.require(:freelancer).permit(:full_name, :social_name,
                                                          :birth_date, :degree, :description,
                                                          :experience, :freelancer_expertise_id))
    if @freelancer.valid?(:profile_completion)
      redirect_to freelancer_path(@freelancer)
    else
      render :edit
    end
  end

  def my_projects
    @proposals = Proposal.where(freelancer: current_freelancer)
  end

  private

  def check_freelancer_identity
    @freelancer = Freelancer.find(params[:id]) if current_freelancer
    return unless @freelancer && @freelancer.email != current_freelancer.email

    flash[:notice] = 'VOCÊ NÃO POSSUI ACESSO AO PROFILE DE OUTROS FREELANCERS'
    redirect_to freelancer_path current_freelancer
  end
end

app/views/freelancers/edit.html.erb
<h1> Formulário de cadastro de perfil pessoal </h1>

<%= form_with model: @freelancer do |f| %>
  <%= f.label :full_name %>
  <%= f.text_field :full_name %>
  <%= @freelancer.errors.full_messages_for(:full_name)[0] %>
  <br />
  <%= f.label :social_name %>
  <%= f.text_field :social_name %>
   <%= @freelancer.errors.full_messages_for(:social_name)[0] %>
  <br />
  <%= f.label :birth_date %>
  <%= f.date_field :birth_date %>
  <%= @freelancer.errors.full_messages_for(:birth_date)[0] %>
  <br />
  <%= f.label :freelancer_expertise_id %>
  <%= f.collection_select :freelancer_expertise_id, FreelancerExpertise.all, :id, :title %>
  <%= @freelancer.errors.full_messages_for(:freelancer_expertise_id)[0] %>
  <br />
  <%= f.label :degree %>
  <%= f.text_field :degree %>
  <%= @freelancer.errors.full_messages_for(:degree)[0] %>
  <br />
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= @freelancer.errors.full_messages_for(:description)[0] %>
  <br />
  <%= f.label :experience %>
  <%= f.text_area :experience %>
  <%= @freelancer.errors.full_messages_for(:experience)[0] %>
  <br />
  <br />
  <%= f.submit %>
<% end %>

app/views/freelancers/my_projects.html.erb
<h3> Meus projetos:</h3>

<% @proposals.each do |proposal| %>
  <%= link_to proposal.project.title, project_path(proposal.project) %>
  <br />
  Descrição: <%= proposal.project.description %>
  <br />
  Status do projeto: <%= Project.human_attribute_name("status.#{proposal.project.status}") %>
  <br />
  Status da proposta: <%= Proposal.human_attribute_name("status.#{proposal.status}")%>
  <br />
  <% if proposal.feedback %>
    Motivo: <%= proposal.feedback.body %>
    <br />
  <% end %>
  <br />
<% end %>

app/views/freelancers/show.html.erb
<%= link_to 'Voltar para homepage', root_path %>
&emsp;
<%= link_to 'Editar meu perfil', edit_freelancer_path %>

<h1> Perfil do freelancer <%= @freelancer.email %> </h1>
<p>
Nome completo: <%= @freelancer.full_name %>
<br />
Nome social: <%= @freelancer.social_name %>
<br />
Data de nascimento: <%= l @freelancer.birth_date %>
<br />
Área de atuação: <%= @freelancer.freelancer_expertise.title %>
<br />
Formação profissional: <%= @freelancer.degree %>
<br />
Descrição: <%= @freelancer.description %>
<br />
Experiência: <%= @freelancer.experience %>
</p>

<h3> Meus projetos realizados: </h3>

<%= render 'projects/summary_list_of_projects', projects: @projects %>