config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  
  devise_for :freelancers
  devise_for :contractors

  namespace :api do
    namespace :v1 do
      resources :projects, only: %i[index show create]
    end
  end

  resources :contractors, only: [:show]
  resources :freelancers, only: [:show, :edit, :update] do
    get 'my_projects', on: :collection
  end

  resources :projects, shallow: true do
    get 'search', on: :collection
    get 'close', on: :member
    get 'finish', on: :member
    resources :proposals do
      post 'accept', on: :member
      post 'deny', on: :member
      post 'forfeit', on: :member
      post 'archive', on: :member
      resource :feedback, only: [:new, :create]
      resources :chats do
        get 'create_new_chat_window', on: :collection
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FreelancingHub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' retira necessidade de bootstrap na aplicação %>
  </head>

  <body>
  <div class="container">
   <% if notice %>
      <div class="alert alert-info" role="alert">
        <%= notice %>
      </div>
    <% end %>
  </div>

   <div class="container">
    <% if alert %>
      <div class="alert alert-warning" role="alert">
        <%= alert %>
      </div>
    <% end %>
  </div>

  <nav class="navbar navbar-light bg-light">
  <% if contractor_signed_in? %>
    Você está logado como contratante || Email: <%= current_contractor.email %>
    &emsp;
    <%= link_to 'Ver meu perfil', contractor_path(current_contractor) %>
    &emsp;
    <%= link_to 'Sair da conta', destroy_contractor_session_path, method: :delete %>
  <% elsif freelancer_signed_in? && current_freelancer.invalid?(:profile_completion) %>
    Você está logado como freelancer || Email: <%= current_freelancer.email %>
    <%= link_to 'Sair da conta', destroy_freelancer_session_path, method: :delete %>
  <% elsif freelancer_signed_in? %>
      <div class="container">
          Você está logado como freelancer || Email: <%= current_freelancer.email %>
          <%= link_to 'Ver meu perfil', freelancer_path(current_freelancer) %>
          <%= link_to 'Meus projetos', my_projects_freelancers_path %>
          <%= link_to 'Sair da conta', destroy_freelancer_session_path, method: :delete %>
      </div>
    <% if current_freelancer.valid?(:profile_completion) %>
      <div class="container">
        <nav class="navbar navbar-light bg-light">
          <%= form_with url: search_projects_path, method: :get do |f| %>
          <%= f.label :search, 'Procurar projeto' %>
          <%= f.text_field :search %>
          <%= f.submit 'Procurar projeto', class: "btn btn-secondary" %>
        </nav>
      </div>
    <% end %>
  <% end %>
  <% else %>
    Você ainda não está logado.
    &emsp;
    <%= link_to 'Entrar como contratante', new_contractor_session_path %>
    &emsp;
    <%= link_to 'Entrar como freelancer', new_freelancer_session_path %>
  <% end %>
  </nav>
  <hr />

    <%= yield %>
  </body>
</html>